### ISSUE TITLE
Missing colour changes to PNGs with an SVG

### ISSUE THREAD

**Issue by lah7** [lah7/ubuntu-mate-colours#1]
Some PNGs, particularly in `gtk-3.0/assets` do not have SVGs for the PNGs, meaning they remain green for some elements, like button borders.

**Our options:**

* Contribute or locate an SVG back to `ubuntu-mate-artwork`.
* Colorize / adjust the colour of the existing raster images.

**See here for some discussion:**

* https://ubuntu-mate.community/t/colour-variants-of-ambiant-radiant-mate-themes/20302/6?u=lah7

**Comment by flexiondotorg** [comment]
There are SVGs for the window controls in `Ambiant-MATE/unity` etc.

**Comment by lah7** [comment]
Thanks, I noticed a few in there. I'm aware @vkareh recently mentioned about improving these window controls for marco. :+1:

Specifically, these are assets missing SVG equivalents:

### metacity-1
- [ ] trough_left.png
- [ ] trough_middle.png
- [ ] trough_right.png
- [ ] trough_unfocused_left.png
- [ ] trough_unfocused_middle.png
- [ ] trough_unfocused_right.png

### gtk-3.0/assets
- [ ] backdrop-button-active-disabled.png
- [ ] backdrop-button-active-hover.png
- [ ] backdrop-button-active.png
- [ ] backdrop-button-disabled.png
- [ ] backdrop-button-hover.png
- [ ] backdrop-button-toolbar-active.png
- [ ] backdrop-button-toolbar.png
- [ ] backdrop-button.png
- [ ] backdrop-combobox-button-disabled.png
- [ ] backdrop-combobox-button.png
- [ ] backdrop-combobox-entry-disabled.png
- [ ] backdrop-combobox-entry.png
- [ ] backdrop-entry-disabled.png
- [ ] backdrop-entry.png
- [ ] button-active-disabled.png
- [ ] button-active-focused-hover.png
- [ ] button-active-focused.png
- [ ] button-active-hover.png
- [ ] button-active.png
- [ ] button-default-focused-hover.png
- [ ] button-default-focused.png
- [ ] button-default-hover.png
- [ ] button-default.png
- [ ] button-disabled.png
- [ ] button-focused-hover.png
- [ ] button-focused.png
- [ ] button-hover.png
- [ ] button-toolbar-active-focused.png
- [ ] button-toolbar-active.png
- [ ] button-toolbar-focused.png
- [ ] button-toolbar.png
- [ ] button.png
- [ ] check-menuitem-dark.png
- [ ] check-menuitem-insensitive-dark.png
- [ ] check-menuitem-insensitive.png
- [ ] check-menuitem-unselected.png
- [ ] check-menuitem.png
- [ ] combobox-arrow-disabled.png
- [ ] combobox-arrow.png
- [ ] combobox-button-disabled.png
- [ ] combobox-button-focused.png
- [ ] combobox-button-pressed-focused.png
- [ ] combobox-button.png
- [ ] combobox-entry-disabled.png
- [ ] combobox-entry-focused.png
- [ ] combobox-entry.png
- [ ] entry-disabled.png
- [ ] entry-focused.png
- [ ] entry-toolbar-focused.png
- [ ] entry-toolbar.png
- [ ] entry.png
- [ ] frame.png
- [ ] menubaritem.png
- [ ] notebook-tab-bottom.png
- [ ] notebook-tab-left.png
- [ ] notebook-tab-right.png
- [ ] notebook-tab-top.png
- [ ] progressbar-horizontal-fill-backdrop.png
- [ ] progressbar-horizontal-fill.png
- [ ] progressbar-horizontal-trough.png
- [ ] progressbar-vertical-fill-backdrop.png
- [ ] progressbar-vertical-fill.png
- [ ] progressbar-vertical-trough.png
- [ ] radiance-backdrop-button-toolbar-active.png
- [ ] radiance-backdrop-button-toolbar.png
- [ ] radiance-button-toolbar-active-focused.png
- [ ] radiance-button-toolbar-active.png
- [ ] radiance-button-toolbar-focused.png
- [ ] radiance-button-toolbar.png
- [ ] radiance-combobox-button-toolbar-focused.png
- [ ] radiance-combobox-button-toolbar-pressed-focused.png
- [ ] radiance-combobox-button-toolbar.png
- [ ] radiance-entry-toolbar-focused.png
- [ ] radiance-entry-toolbar.png
- [ ] radiance-menubaritem.png
- [ ] radiance-scrollbar_handle_vertical.png
- [ ] radiance-scrollbar_handle.png
- [ ] radiance-slider_backdrop.png
- [ ] radiance-slider_insensitive_backdrop.png
- [ ] radiance-slider_insensitive.png
- [ ] radiance-slider_prelight_vertical.png
- [ ] radiance-slider_prelight.png
- [ ] radiance-slider_vertical_backdrop.png
- [ ] radiance-slider_vertical_insensitive_backdrop.png
- [ ] radiance-slider_vertical_insensitive.png
- [ ] radiance-slider_vertical.png
- [ ] radiance-slider.png
- [ ] radio-menuitem-dark.png
- [ ] radio-menuitem-insensitive-dark.png
- [ ] radio-menuitem-insensitive.png
- [ ] radio-menuitem.png
- [ ] scale-horizontal-fill-backdrop.png
- [ ] scale-horizontal-fill-disabled.png
- [ ] scale-horizontal-fill.png
- [ ] scale-horizontal-trough-backdrop.png
- [ ] scale-horizontal-trough-disabled.png
- [ ] scale-horizontal-trough.png
- [ ] scale-vertical-fill-backdrop.png
- [ ] scale-vertical-fill-disabled.png
- [ ] scale-vertical-fill.png
- [ ] scale-vertical-trough-backdrop.png
- [ ] scale-vertical-trough-disabled.png
- [ ] scale-vertical-trough.png
- [ ] slider-horizontal-disabled.png
- [ ] slider-horizontal-focused-hover.png
- [ ] slider-horizontal-focused.png
- [ ] slider-horizontal-hover.png
- [ ] slider-horizontal.png
- [ ] slider-vertical-disabled.png
- [ ] slider-vertical-focused-hover.png
- [ ] slider-vertical-focused.png
- [ ] slider-vertical-hover.png
- [ ] slider-vertical.png
- [ ] switch-button-off-disabled.png
- [ ] switch-button-off.png
- [ ] switch-button-on-disabled.png
- [ ] switch-button-on.png
- [ ] switch-trough-disabled.png
- [ ] switch-trough-focused.png
- [ ] switch-trough-off.png
- [ ] switch-trough-on.png
- [ ] switch-trough-toolbar-off.png
- [ ] switch-trough-toolbar-on.png

**Comment by flexiondotorg** [comment]
When you say "missing assets" do you mean assets for which we do not have svg files?

**Comment by lah7** [comment]
Correct. I don't know if they were originally created as PNGs **_or_** if they were exported from SVGs that were never committed. The same files can't be seen with SVGs in [Ambiance (bzr)](http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/files/head:/Ambiance/) nor a fork like [Ambiance-Colors (deb - 16.04)](https://www.ravefinity.com/p/download-ambiance-radiance-colors.html).

**Comment by lah7** [comment]
Closing old issue as we recoloured the PNGs for years.

Having SVGs in place of PNGs is still a trivial _nice to have_ for improving resolution, so any one in the future reading this is welcome to take up that task. Personally it's not too important to me as the theme declines in popularity.
