### ISSUE TITLE
Error with volume indicator popup

### ISSUE THREAD

**Issue by cerisezero** [lah7/ubuntu-mate-colours#14]
Running 19.04. On changing the volume via keyboard controls, the icon that pops up is poorly scaled and appears completely different to that displayed using stock MATE themes - in fact, it appears to be from the Humanity theme?
This seems to be common across variants that I've tried. The stock volume control images are still in the new theme icon sets, so I'm unsure what would change here?

![SoundIssue](https://user-images.githubusercontent.com/56359596/66499220-4a6bbc00-eab7-11e9-892b-61d5ec85de1a.png) 
Modified
![SoundIssue2](https://user-images.githubusercontent.com/56359596/66499682-31173f80-eab8-11e9-8ab3-8a2d718ea001.png)
Stock MATE

**Comment by lah7** [comment]
I'll guess the file optimisation is the cause of this -- I added a last step where the generator will remove "unmodified" files and rely on icon inheritance to try and reduce the disk space for installed colour themes.

Two options:

* Disable the clean-up, so all themes contain a copy of the original Ambiant/Radiant-MATE icons.
  * **Adds 16.9 MB per icon theme!**
* Find out the icons that need to be put back into the colour theme and [make an exception along with this one](https://github.com/lah7/ubuntu-mate-colours/blob/4aa86eb0a91acf60f5a49a64074e1ce29e09d87f/ubuntu-mate-colours-generator#L513-L515).

I bet the keyboard brightness pop up would be affected too.

**Comment by cerisezero** [comment]
Unable to confirm one way or the other on the keyboard brightness, not a popup I'm familiar with. However, the laptop screen brightness popup seems to be unaffected at first glance?

**Comment by lah7** [comment]
It looks like might be a regression in the latest versions (19.10.10) of Ambiant/Radiant-MATE.

I just tried 19.10 in a live session with stock themes and it's showing the ugly icon.

**Comment by lah7** [comment]
Found the commit in the original theme, it appears these are the new icons. :disappointed: 

> Add full color volume icons for use in applications and the OSD. 

https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/4718ee046ca9bd61815f049d27711a1c50553182

**Comment by lah7** [comment]
I've added a "patch" step so that the mono icons we like are used in the OSD.

The only **_potential_** pitfall are the applications that use a low/medium/high volume icon - but I've yet to see an app that suffers from this:

![Screenshot_20191101_113348](https://user-images.githubusercontent.com/13032135/68022186-7b48a680-fc9b-11e9-8d10-22035eac238e.png)

(This is from `gtk3-widget-factory` for testing UI controls)
