### ISSUE TITLE
Missing colour definitions/changes in icons

### ISSUE THREAD

**Issue by cerisezero** [lah7/ubuntu-mate-colours#15]
Very minor details; there are a couple of standard colours in the SVGs that the themed versions don't have changed.
#2e4705: a very dark green colour in system-file-manager.svg (Caja icon) and ooo-web.svg (OpenOffice file format?)
#d9edb9: a highlight colour on go-up/down/bottom/etc.svg

**Comment by lah7** [comment]
274274f81001e7d50e6d401cc0fb4cfa12fa766a (#16) includes fixes for these colours.
