### ISSUE TITLE
Yellow colour should use BLACK text instead of white in things like Ubuntu MATE's menu and Caja

### ISSUE THREAD

**Issue by djvar94** [lah7/ubuntu-mate-colours#21]
The current white text on the yellow highlight is really annoying as they're both light colours, it makes it so hard to read, very inconsistent and very bad looking. Here I attach a couple of screenshots I made to give the idea of what I mean. By the way it also affects areas like Firefox's address bar when selecting text, text editors, Evolution, and all the other GTK+3 related programs. Please fix this.

![Screenshot at 2020-04-21 18-14-18](https://user-images.githubusercontent.com/48367983/79894060-d19dd300-83fc-11ea-8530-8ade9d83a121.png)
-------------------------------------------------------------------------------------------------------------------------
![Screenshot at 2020-04-21 20-27-44](https://user-images.githubusercontent.com/48367983/79905847-ca7fc080-840e-11ea-8b00-b008a2de2228.png)

**Comment by lah7** [comment]
Thanks for the feedback, agreed on the poor contrast.

I've amended the theme - packages will be updated later today.

**Comment by djvar94** [comment]
It's great. Though the same problem is now in the Dark version of the theme. Please fix that one too thanks.

**Comment by lah7** [comment]
Fixed. :hammer: :package:  Packages are in the process of being rebuilt.
