### ISSUE TITLE
[20.04] - Ambiant/Radiant-MATE - Plank themes are not supported

### ISSUE THREAD

**Issue by dianawhite42** [lah7/ubuntu-mate-colours#23]
### Describe the problem 
Plank themes are not supported. On a base install using a panel layout like Cupertino that makes use of Plank, changing theme colors does not change the Plank theme. Plank is always the Ubuntu Mate green.

### Expected behaviour
ubuntu-mate-colors should generate/install and apply a new Plank theme to match the color selected by the user. 

### Which themes are affected?

- [x] Ambiant-MATE
- [x] Ambiant-MATE-Dark
- [x] Radiant-MATE

- [ ] This affects [ubuntu-mate/ubuntu-mate-artwork](https://github.com/ubuntu-mate/ubuntu-mate-artwork)

### Screenshots
Current (with aqua theme applied):
![problem1](https://user-images.githubusercontent.com/30417673/91170416-daeac500-e6a6-11ea-8822-39371ffd85e4.png)
Expected:
![expected2](https://user-images.githubusercontent.com/30417673/91170422-dc1bf200-e6a6-11ea-969b-eff42baefdcc.png)

### Release Version
20.04.1

**Comment by dianawhite42** [comment]
Lines 12-18 of a Plank theme have the relevant code to edit. This is my current Aqua dock theme: 
```
OuterStrokeColor=45;;172;;212;;100
#The starting color (RGBA) of the fill gradient.
FillStartColor=45;;172;;212;;100
#The ending color (RGBA) of the fill gradient.
FillEndColor=45;;172;;212;;200
#The color (RGBA) of the inner stroke.
InnerStrokeColor=45;;172;;212;;100
```

**Comment by lah7** [comment]
Thanks, I completely missed Plank, but it is now supported. :slightly_smiling_face: (New packages will be released later today)

Even though we can't automatically set/overwrite the dock's theme, it will be listed as a new theme for selection.

![Screenshot_20200825_160222](https://user-images.githubusercontent.com/13032135/91191187-5de23e80-e6ec-11ea-9799-2afb81e99a9b.png)
