### ISSUE TITLE
Snapping the Color Themes

### ISSUE THREAD

**Issue by iamjameswalters** [lah7/ubuntu-mate-colours#27]
Hi there!

I use one of the 🔵 blue themes, and I decided to [make a snap of it](https://snapcraft.io/mate-themes-blue) so that my snap apps would match the rest of my system better. I actually [have a project](https://github.com/iamjameswalters/mate-color-themes-snap) with a python script to generate snapcraft YAMLs for all the rest of the colors. 🌈

I thought I would offer this to you, since these are your themes. If you'd like to snap them 🤏, let me know and I'll open a PR here with my work! Or if that sounds like a chore, no worries, I'm happy to maintain the snaps. 🙂

**Comment by lah7** [comment]
Starting in 22.04, Ubuntu MATE will no longer ship with the Ambiant-MATE family of themes, [While officially gone, I "forked" and given them a new home](https://github.com/lah7/Ambiant-MATE/). They'll be bundling colour variations of Yaru-MATE, as it's very close to Yaru upstream now. Therefore, this project will discontinue the production of Yaru-MATE colours.

That does leave this snap in an awkward position. According to its metrics, there's only 4 or 5 users. 😞 

It doesn't look like renaming or deleting a snap is possible, so I'm thinking to deprecate `ubuntu-mate-colours` and have a new `ambiant-mate-colours` snap instead, reusing the existing YAML. Any one using Yaru-MATE colours would probably switch to Yaru-MATE's official snap when that's ready. What do you think?

**Comment by iamjameswalters** [comment]
I think that probably sounds like the right track. You should be able to strip out all the Yaru stuff and make the snap leaner, to boot. 🥾

Glad the Yaru colors will be handled by the core team--is this owing to Ubuntu's new feature for selecting your own accent color, I wonder? 🤔 Would make sense for the flavors to want to implement that as well, any users coming over from Ubuntu might expect that behavior.

I'm not surprised that user count is low--I was expecting that to uptick after the release of 22.04 when I imagined anyone with a new install who installed a color theme would have the snap auto-downloaded. Maybe I'll be wrong though?

**Comment by lah7** [comment]
Yes, Yaru's accent colour support arrives at a good time, otherwise I would need to re-update the scripts now that Yaru-MATE is in Yaru's `master` with new fixes available. Up to now, the MATE variant was in a separate branch.

The low user count is probably because users have to go out of their way to find this repository and install the snap. It wasn't integrated into Welcome so it wasn't an automatic install.
