### ISSUE TITLE
Ambiant-MATE-Dark icons missing

### ISSUE THREAD

**Issue by vkareh** [lah7/ubuntu-mate-colours#6]
Both Ambiant-MATE and Radiant-MATE work on all the colors. The Ambiant-MATE-Dark, however, seems to be missing the icons:

![Screenshot at 2019-10-07 12-27-20](https://user-images.githubusercontent.com/259780/66330259-03869680-e8fe-11e9-9497-1686a35d828b.png)

I installed by doing:
```
$ sudo add-apt-repository ppa:lah7/ubuntu-mate-colours
$ sudo apt install ubuntu-mate-colours-generator ubuntu-mate-colours-all
```

**Comment by lah7** [comment]
Since there's only two icon themes - Ambiant-MATE and Radiant-MATE - the `-Dark` is supposed to be removed so there isn't a duplication of icons.

I'll get that fixed up and rebuild the packages.

**Comment by lah7** [comment]
:package: New packages are in the process of being re-built. These include the fix for the missing icons.
