### ISSUE TITLE
Some button prelights are not colored

### ISSUE THREAD

**Issue by vkareh** [lah7/ubuntu-mate-colours#7]
Selected Ambiant-MATE-Orange and notice the link on the bottom left corner is green, same with the highlight on the Help button

![Screenshot at 2019-10-07 12-32-01](https://user-images.githubusercontent.com/259780/66330577-ad662300-e8fe-11e9-99fa-c214af7114a5.png)

**Comment by lah7** [comment]
The button highlight is certainly due to #1 - the generator isn't processing PNG files yet.

Will need to find the location of that stray green so it's swapped out.
